### Cabinet route
GET http://localhost:3000/cabinet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc1NTk3ODYsImV4cCI6MTYxNzU1OTg0NiwiYXVkIjoiNjA2YTAwZTc3MTkwNzUyN2U0YTFkNjljIiwiaXNzIjoiZGlhcnkucnUifQ.oS9g5x7H_OhVzHRnERzCBZSoIIedReyMNk75MOrWLhw

### Register route
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "zzz@d.ru",
    "password": "test12345678",
    "passwordConfirm": "test12345678"
}

### Login route
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "zzz@d.ru",
    "password": "test12345678"
}

### Refresh token route
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc1NTk3ODYsImV4cCI6MTYxNzU2MzM4NiwiYXVkIjoiNjA2YTAwZTc3MTkwNzUyN2U0YTFkNjljIiwiaXNzIjoiZGlhcnkucnUifQ.TtXC9QuscucFEjmoSyp6fJ4wN2Cjb2oGEBMn-7QvX1Q"
}